import {
  Archive,
  BadgeCheck,
  BookOpen,
  Cookie,
  CreditCard,
  Database,
  FileText,
  FlaskConical,
  KeyRound,
  Lock,
  Plug,
  Scale,
  ShieldCheck,
  Siren,
  Sparkles,
  TriangleAlert,
  type LucideIcon,
} from "lucide-react";
import type { PolicyIcon } from "@/lib/policies";

export const POLICY_ICONS: Record<PolicyIcon, LucideIcon> = {
  book: BookOpen,
  file: FileText,
  shield: ShieldCheck,
  badge: BadgeCheck,
  sparkles: Sparkles,
  alert: TriangleAlert,
  card: CreditCard,
  lock: Lock,
  cookie: Cookie,
  database: Database,
  key: KeyRound,
  siren: Siren,
  archive: Archive,
  plug: Plug,
  flask: FlaskConical,
  scale: Scale,
};
